pragma Singleton

import QtQuick

QtObject {
    property string iconmoon: iconmoonFontLoader.name
    property FontLoader iconmoonFontLoader: FontLoader {
        source: "qrc:/fonts/UI/Fonts/IcoMoon/fonts/icomoon.ttf"
    }

    property string exc_logo:       String.fromCharCode(parseInt('e973', 16))
    property string face_id:        String.fromCharCode(parseInt('e971', 16))
    property string sad:            String.fromCharCode(parseInt('e970', 16))
    property string mining:         String.fromCharCode(parseInt('e96f', 16))
    property string user:           String.fromCharCode(parseInt('e96e', 16))
    property string subscribe:      String.fromCharCode(parseInt('e96d', 16))
    property string settings:       String.fromCharCode(parseInt('e96c', 16))
    property string key:            String.fromCharCode(parseInt('e96b', 16))
    property string check:          String.fromCharCode(parseInt('e96a', 16))
    property string fault_tx:       String.fromCharCode(parseInt('e969', 16))
    property string desigh:         String.fromCharCode(parseInt('e968', 16))
    property string attention:      String.fromCharCode(parseInt('e963', 16))
    property string raccoon:        String.fromCharCode(parseInt('e965', 16))
    property string storage:        String.fromCharCode(parseInt('e966', 16))
    property string wallet:         String.fromCharCode(parseInt('e967', 16))
    property string video:          String.fromCharCode(parseInt('e962', 16))
    property string gif:            String.fromCharCode(parseInt('e961', 16))
    property string rendering:      String.fromCharCode(parseInt('e95e', 16))
    property string license:        String.fromCharCode(parseInt('e95f', 16))
    property string dark_theme:     String.fromCharCode(parseInt('e95c', 16))
    property string light_theme:    String.fromCharCode(parseInt('e95d', 16))
    property string export_profile: String.fromCharCode(parseInt('e957', 16))
    property string light_chain:    String.fromCharCode(parseInt('e959', 16))
    property string connections:    String.fromCharCode(parseInt('e95b', 16))
    property string update:         String.fromCharCode(parseInt('e95a', 16))
    property string dfs:            String.fromCharCode(parseInt('e958', 16))
    property string file_add:       String.fromCharCode(parseInt('e948', 16))
    property string file_upload:    String.fromCharCode(parseInt('e956', 16))
    property string image_raccoon:  String.fromCharCode(parseInt('e955', 16))
    property string shield:         String.fromCharCode(parseInt('e952', 16))
    property string folder:         String.fromCharCode(parseInt('e953', 16))
    property string send:           String.fromCharCode(parseInt('e951', 16))
    property string save:           String.fromCharCode(parseInt('e949', 16))
    property string heart:          String.fromCharCode(parseInt('e945', 16))
    property string comment:        String.fromCharCode(parseInt('e944', 16))
    property string star:           String.fromCharCode(parseInt('e946', 16))
    property string community:      String.fromCharCode(parseInt('e94d', 16))
    property string location:       String.fromCharCode(parseInt('e94c', 16))
    property string more:           String.fromCharCode(parseInt('e941', 16))
    property string circle:         String.fromCharCode(parseInt('e940', 16))
    property string selected:       String.fromCharCode(parseInt('e934', 16))
    property string file:           String.fromCharCode(parseInt('e93f', 16))
    property string open:           String.fromCharCode(parseInt('e93e', 16))
    property string download:       String.fromCharCode(parseInt('e93d', 16))
    property string settings_panel: String.fromCharCode(parseInt('e93a', 16))
    property string status:         String.fromCharCode(parseInt('e93b', 16))
    property string back_in_circle: String.fromCharCode(parseInt('e937', 16))
    property string lock_open:      String.fromCharCode(parseInt('e933', 16))
    property string camera:         String.fromCharCode(parseInt('e936', 16))
    property string flash:          String.fromCharCode(parseInt('e935', 16))
    property string gallery:        String.fromCharCode(parseInt('e932', 16))
    property string camera_view:    String.fromCharCode(parseInt('e931', 16))
    property string message_create: String.fromCharCode(parseInt('e930', 16))
    property string like_story:     String.fromCharCode(parseInt('e91e', 16))
    property string share_story:    String.fromCharCode(parseInt('e92f', 16))
    property string reply:          String.fromCharCode(parseInt('e92e', 16))
    property string plus:           String.fromCharCode(parseInt('e92d', 16))
    property string share:          String.fromCharCode(parseInt('e92c', 16))
    property string withdrawal:     String.fromCharCode(parseInt('e92b', 16))
    property string import_keystore:String.fromCharCode(parseInt('e92a', 16))
    property string close_circle:   String.fromCharCode(parseInt('e900', 16))
    property string close:          String.fromCharCode(parseInt('e929', 16))
    property string down:           String.fromCharCode(parseInt('e927', 16))
    property string edit:           String.fromCharCode(parseInt('e926', 16))
    property string message:        String.fromCharCode(parseInt('e960', 16))
    property string navigation:     String.fromCharCode(parseInt('e924', 16))
    property string verify:         String.fromCharCode(parseInt('e923', 16))
    property string account:        String.fromCharCode(parseInt('e920', 16))
    property string back:           String.fromCharCode(parseInt('e919', 16))
    property string arrow_back:     String.fromCharCode(parseInt('e91a', 16))
    property string attach:         String.fromCharCode(parseInt('e902', 16))
    property string happy:          String.fromCharCode(parseInt('e903', 16))
    property string trash:          String.fromCharCode(parseInt('e904', 16))
    property string image:          String.fromCharCode(parseInt('e905', 16))
    property string funnel:         String.fromCharCode(parseInt('e906', 16))
    property string copy:           String.fromCharCode(parseInt('e907', 16))
    property string google:         String.fromCharCode(parseInt('e908', 16))
    property string visability:     String.fromCharCode(parseInt('e909', 16))
    property string lock_close:     String.fromCharCode(parseInt('e90a', 16))
    property string information:    String.fromCharCode(parseInt('e90b', 16))
    property string create:         String.fromCharCode(parseInt('e90c', 16))
    property string checkmark:      String.fromCharCode(parseInt('e90d', 16))
    property string checkmark_done: String.fromCharCode(parseInt('e90e', 16))
    property string search:         String.fromCharCode(parseInt('e90f', 16))
    property string menu:           String.fromCharCode(parseInt('e910', 16))
    property string chat_settings:  String.fromCharCode(parseInt('e910', 16))
    property string arrow_forward:  String.fromCharCode(parseInt('e911', 16))
    property string home:           String.fromCharCode(parseInt('e94b', 16))
    property string chatbox:        String.fromCharCode(parseInt('e913', 16))
    property string people:         String.fromCharCode(parseInt('e915', 16))
    property string bookmarks:      String.fromCharCode(parseInt('e916', 16))
    property string card:           String.fromCharCode(parseInt('e918', 16))
    property string bell:           String.fromCharCode(parseInt('e94a', 16))
    property string user_create:    String.fromCharCode(parseInt('e918', 16))
    property string frame:          String.fromCharCode(parseInt('e919', 16))
    property string bookmark:       String.fromCharCode(parseInt('e91c', 16))
    property string like:           String.fromCharCode(parseInt('e94f', 16))
    property string dislike:        String.fromCharCode(parseInt('e950', 16))
    property string login:          String.fromCharCode(parseInt('e91f', 16))
    property string logout:         String.fromCharCode(parseInt('e91f', 16))
    property string user_add:       String.fromCharCode(parseInt('e928', 16))
    property string logo:           String.fromCharCode(parseInt('e921', 16))
    property string volume_mute:    String.fromCharCode(parseInt('ea2a', 16))
    property string volume:         String.fromCharCode(parseInt('ea27', 16))
    property string play:           String.fromCharCode(parseInt('ea1c', 16))
    property string pause:          String.fromCharCode(parseInt('ea1d', 16))
}
