pragma Singleton

import QtQuick

Item {
    function getFlagByNameCountry(country) {
        switch(country) {
        case "Abkhazia": return "qrc:/flags/UI/Images/flags/abkhazia.png";
        case "Afghanistan": return "qrc:/flags/UI/Images/flags/afghanistan.png";
        case "Aland Islands": return "qrc:/flags/UI/Images/flags/aland islands.png";
        case "Albania": return "qrc:/flags/UI/Images/flags/albania.png";
        case "Algeria": return "qrc:/flags/UI/Images/flags/algeria.png";
        case "American Samoa": return "qrc:/flags/UI/Images/flags/american samoa.png";
        case "Andorra": return "qrc:/flags/UI/Images/flags/andorra.png";
        case "Angola": return "qrc:/flags/UI/Images/flags/angola.png";
        case "Anguilla": return "qrc:/flags/UI/Images/flags/anguilla.png";
        case "Antigua and Barbuda": return "qrc:/flags/UI/Images/flags/antigua and barbuda.png";
        case "Argentina": return "qrc:/flags/UI/Images/flags/argentina.png";
        case "Armenia": return "qrc:/flags/UI/Images/flags/armenia.png";
        case "Aruba": return "qrc:/flags/UI/Images/flags/aruba.png";
        case "Australia": return "qrc:/flags/UI/Images/flags/australia.png";
        case "Austria": return "qrc:/flags/UI/Images/flags/austria.png";
        case "Azerbaijan": return "qrc:/flags/UI/Images/flags/azerbaijan.png";
        case "Azores Islands": return "qrc:/flags/UI/Images/flags/azores islands.png";
        case "Bahamas": return "qrc:/flags/UI/Images/flags/bahamas.png";
        case "Bahrain": return "qrc:/flags/UI/Images/flags/bahrain.png";
        case "Balearic Islands": return "qrc:/flags/UI/Images/flags/balearic islands.png";
        case "Bangladesh": return "qrc:/flags/UI/Images/flags/bangladesh.png";
        case "Barbados": return "qrc:/flags/UI/Images/flags/barbados.png";
        case "Basque Country": return "qrc:/flags/UI/Images/flags/basque country.png";
        case "Belarus": return "qrc:/flags/UI/Images/flags/belarus.png";
        case "Belgium": return "qrc:/flags/UI/Images/flags/belgium.png";
        case "Belize": return "qrc:/flags/UI/Images/flags/belize.png";
        case "Benin": return "qrc:/flags/UI/Images/flags/benin.png";
        case "Bermuda": return "qrc:/flags/UI/Images/flags/bermuda.png";
        case "Bhutan": return "qrc:/flags/UI/Images/flags/bhutan.png";
        case "Bolivia": return "qrc:/flags/UI/Images/flags/bolivia.png";
        case "Bonaire": return "qrc:/flags/UI/Images/flags/bonaire.png";
        case "Bosnia and Herzegovina": return "qrc:/flags/UI/Images/flags/bosnia and herzegovina.png";
        case "Botswana": return "qrc:/flags/UI/Images/flags/botswana.png";
        case "Brazil": return "qrc:/flags/UI/Images/flags/brazil.png";
        case "British Columbia": return "qrc:/flags/UI/Images/flags/british columbia.png";
        case "British Indian Ocean Territory": return "qrc:/flags/UI/Images/flags/british indian ocean territory.png";
        case "British Virgin Islands": return "qrc:/flags/UI/Images/flags/british virgin islands.png";
        case "Brunei": return "qrc:/flags/UI/Images/flags/brunei.png";
        case "Bulgaria": return "qrc:/flags/UI/Images/flags/bulgaria.png";
        case "Burkina Faso": return "qrc:/flags/UI/Images/flags/burkina faso.png";
        case "Burundi": return "qrc:/flags/UI/Images/flags/burundi.png";
        case "Cambodia": return "qrc:/flags/UI/Images/flags/cambodia.png";
        case "Cameroon": return "qrc:/flags/UI/Images/flags/cameroon.png";
        case "Canada": return "qrc:/flags/UI/Images/flags/canada.png";
        case "Canary Islands": return "qrc:/flags/UI/Images/flags/canary islands.png";
        case "Cape Verde": return "qrc:/flags/UI/Images/flags/cape verde.png";
        case "Cayman Islands": return "qrc:/flags/UI/Images/flags/cayman islands.png";
        case "Central African Republic": return "qrc:/flags/UI/Images/flags/central african republic.png";
        case "Ceuta": return "qrc:/flags/UI/Images/flags/ceuta.png";
        case "Chad": return "qrc:/flags/UI/Images/flags/chad.png";
        case "Chile": return "qrc:/flags/UI/Images/flags/chile.png";
        case "China": return "qrc:/flags/UI/Images/flags/china.png";
        case "Cocos Island": return "qrc:/flags/UI/Images/flags/cocos island.png";
        case "Colombia": return "qrc:/flags/UI/Images/flags/colombia.png";
        case "Comoros": return "qrc:/flags/UI/Images/flags/comoros.png";
        case "Cook Islands": return "qrc:/flags/UI/Images/flags/cook islands.png";
        case "Corsica": return "qrc:/flags/UI/Images/flags/corsica.png";
        case "Costa Rica": return "qrc:/flags/UI/Images/flags/costa rica.png";
        case "Croatia": return "qrc:/flags/UI/Images/flags/croatia.png";
        case "Cuba": return "qrc:/flags/UI/Images/flags/cuba.png";
        case "Curacao": return "qrc:/flags/UI/Images/flags/curacao.png";
        case "Cyprus": return "qrc:/flags/UI/Images/flags/cyprus.png";
        case "Czech Republic": return "qrc:/flags/UI/Images/flags/czech republic.png";
        case "Democratic Republic of Congo": return "qrc:/flags/UI/Images/flags/democratic republic of congo.png";
        case "Denmark": return "qrc:/flags/UI/Images/flags/denmark.png";
        case "Djibouti": return "qrc:/flags/UI/Images/flags/djibouti.png";
        case "Dominica": return "qrc:/flags/UI/Images/flags/dominica.png";
        case "Dominican Republic": return "qrc:/flags/UI/Images/flags/dominican republic.png";
        case "East Timor": return "qrc:/flags/UI/Images/flags/east timor.png";
        case "Ecuador": return "qrc:/flags/UI/Images/flags/ecuador.png";
        case "Egypt": return "qrc:/flags/UI/Images/flags/egypt.png";
        case "El Salvador": return "qrc:/flags/UI/Images/flags/el salvador.png";
        case "England": return "qrc:/flags/UI/Images/flags/england.png";
        case "Equatorial Guinea": return "qrc:/flags/UI/Images/flags/equatorial guinea.png";
        case "Eritrea": return "qrc:/flags/UI/Images/flags/eritrea.png";
        case "Estonia": return "qrc:/flags/UI/Images/flags/estonia.png";
        case "Ethiopia": return "qrc:/flags/UI/Images/flags/ethiopia.png";
        case "European Union": return "qrc:/flags/UI/Images/flags/european union.png";
        case "Falkland Islands": return "qrc:/flags/UI/Images/flags/falkland islands.png";
        case "Faroe Islands": return "qrc:/flags/UI/Images/flags/faroe islands.png";
        case "Fiji": return "qrc:/flags/UI/Images/flags/fiji.png";
        case "Finland": return "qrc:/flags/UI/Images/flags/finland.png";
        case "France": return "qrc:/flags/UI/Images/flags/france.png";
        case "French Polynesia": return "qrc:/flags/UI/Images/flags/french polynesia.png";
        case "Gabon": return "qrc:/flags/UI/Images/flags/gabon.png";
        case "Galapagos Islands": return "qrc:/flags/UI/Images/flags/galapagos islands.png";
        case "Gambia": return "qrc:/flags/UI/Images/flags/gambia.png";
        case "Georgia": return "qrc:/flags/UI/Images/flags/georgia.png";
        case "Germany": return "qrc:/flags/UI/Images/flags/germany.png";
        case "Ghana": return "qrc:/flags/UI/Images/flags/ghana.png";
        case "Gibraltar": return "qrc:/flags/UI/Images/flags/gibraltar.png";
        case "Greece": return "qrc:/flags/UI/Images/flags/greece.png";
        case "Greenland": return "qrc:/flags/UI/Images/flags/greenland.png";
        case "Grenada": return "qrc:/flags/UI/Images/flags/grenada.png";
        case "Guam": return "qrc:/flags/UI/Images/flags/guam.png";
        case "Guatemala": return "qrc:/flags/UI/Images/flags/guatemala.png";
        case "Guernsey": return "qrc:/flags/UI/Images/flags/guernsey.png";
        case "Guinea Bissau": return "qrc:/flags/UI/Images/flags/guinea bissau.png";
        case "Guinea": return "qrc:/flags/UI/Images/flags/guinea.png";
        case "Guyana": return "qrc:/flags/UI/Images/flags/guyana.png";
        case "Haiti": return "qrc:/flags/UI/Images/flags/haiti.png";
        case "Hawaii": return "qrc:/flags/UI/Images/flags/hawaii.png";
        case "Honduras": return "qrc:/flags/UI/Images/flags/honduras.png";
        case "Hong Kong": return "qrc:/flags/UI/Images/flags/hong kong.png";
        case "Hungary": return "qrc:/flags/UI/Images/flags/hungary.png";
        case "Iceland": return "qrc:/flags/UI/Images/flags/iceland.png";
        case "India": return "qrc:/flags/UI/Images/flags/india.png";
        case "Indonesia": return "qrc:/flags/UI/Images/flags/indonesia.png";
        case "Iran": return "qrc:/flags/UI/Images/flags/iran.png";
        case "Iraq": return "qrc:/flags/UI/Images/flags/iraq.png";
        case "Ireland": return "qrc:/flags/UI/Images/flags/ireland.png";
        case "Isle of Man": return "qrc:/flags/UI/Images/flags/isle of man.png";
        case "Israel": return "qrc:/flags/UI/Images/flags/israel.png";
        case "Italy": return "qrc:/flags/UI/Images/flags/italy.png";
        case "Ivory Coast": return "qrc:/flags/UI/Images/flags/ivory coast.png";
        case "Jamaica": return "qrc:/flags/UI/Images/flags/jamaica.png";
        case "Japan": return "qrc:/flags/UI/Images/flags/japan.png";
        case "Jersey": return "qrc:/flags/UI/Images/flags/jersey.png";
        case "Jordan": return "qrc:/flags/UI/Images/flags/jordan.png";
        case "Kazakhstan": return "qrc:/flags/UI/Images/flags/kazakhstan.png";
        case "Kenya": return "qrc:/flags/UI/Images/flags/kenya.png";
        case "Kiribati": return "qrc:/flags/UI/Images/flags/kiribati.png";
        case "Kosovo": return "qrc:/flags/UI/Images/flags/kosovo.png";
        case "Kuwait": return "qrc:/flags/UI/Images/flags/kuwait.png";
        case "Kyrgyzstan": return "qrc:/flags/UI/Images/flags/kyrgyzstan.png";
        case "Laos": return "qrc:/flags/UI/Images/flags/laos.png";
        case "Latvia": return "qrc:/flags/UI/Images/flags/latvia.png";
        case "Lebanon": return "qrc:/flags/UI/Images/flags/lebanon.png";
        case "Lesotho": return "qrc:/flags/UI/Images/flags/lesotho.png";
        case "Liberia": return "qrc:/flags/UI/Images/flags/liberia.png";
        case "Libya": return "qrc:/flags/UI/Images/flags/libya.png";
        case "Liechtenstein": return "qrc:/flags/UI/Images/flags/liechtenstein.png";
        case "Lithuania": return "qrc:/flags/UI/Images/flags/lithuania.png";
        case "Luxembourg": return "qrc:/flags/UI/Images/flags/luxembourg.png";
        case "Macao": return "qrc:/flags/UI/Images/flags/macao.png";
        case "Madagascar": return "qrc:/flags/UI/Images/flags/madagascar.png";
        case "Madeira": return "qrc:/flags/UI/Images/flags/madeira.png";
        case "Malawi": return "qrc:/flags/UI/Images/flags/malawi.png";
        case "Malaysia": return "qrc:/flags/UI/Images/flags/malaysia.png";
        case "Maldives": return "qrc:/flags/UI/Images/flags/maldives.png";
        case "Mali": return "qrc:/flags/UI/Images/flags/mali.png";
        case "Malta": return "qrc:/flags/UI/Images/flags/malta.png";
        case "Marshall Island": return "qrc:/flags/UI/Images/flags/marshall island.png";
        case "Martinique": return "qrc:/flags/UI/Images/flags/martinique.png";
        case "Mauritania": return "qrc:/flags/UI/Images/flags/mauritania.png";
        case "Mauritius": return "qrc:/flags/UI/Images/flags/mauritius.png";
        case "Melilla": return "qrc:/flags/UI/Images/flags/melilla.png";
        case "Mexico": return "qrc:/flags/UI/Images/flags/mexico.png";
        case "Micronesia": return "qrc:/flags/UI/Images/flags/micronesia.png";
        case "Moldova": return "qrc:/flags/UI/Images/flags/moldova.png";
        case "Monaco": return "qrc:/flags/UI/Images/flags/monaco.png";
        case "Mongolia": return "qrc:/flags/UI/Images/flags/mongolia.png";
        case "Montenegro": return "qrc:/flags/UI/Images/flags/montenegro.png";
        case "Montserrat": return "qrc:/flags/UI/Images/flags/montserrat.png";
        case "Morocco": return "qrc:/flags/UI/Images/flags/morocco.png";
        case "Mozambique": return "qrc:/flags/UI/Images/flags/mozambique.png";
        case "Myanmar": return "qrc:/flags/UI/Images/flags/myanmar.png";
        case "Namibia": return "qrc:/flags/UI/Images/flags/namibia.png";
        case "NATO": return "qrc:/flags/UI/Images/flags/nato.png";
        case "Nauru": return "qrc:/flags/UI/Images/flags/nauru.png";
        case "Nepal": return "qrc:/flags/UI/Images/flags/nepal.png";
        case "Netherlands": return "qrc:/flags/UI/Images/flags/netherlands.png";
        case "New Zealand": return "qrc:/flags/UI/Images/flags/new zealand.png";
        case "Nicaragua": return "qrc:/flags/UI/Images/flags/nicaragua.png";
        case "Niger": return "qrc:/flags/UI/Images/flags/niger.png";
        case "Nigeria": return "qrc:/flags/UI/Images/flags/nigeria.png";
        case "Niue": return "qrc:/flags/UI/Images/flags/niue.png";
        case "Norfolk Island": return "qrc:/flags/UI/Images/flags/norfolk island.png";
        case "North Korea": return "qrc:/flags/UI/Images/flags/north korea.png";
        case "Northern Cyprus": return "qrc:/flags/UI/Images/flags/northern cyprus.png";
        case "Northern Marianas Islands": return "qrc:/flags/UI/Images/flags/northern marianas islands.png";
        case "Norway": return "qrc:/flags/UI/Images/flags/norway.png";
        case "Oman": return "qrc:/flags/UI/Images/flags/oman.png";
        case "Orkney Islands": return "qrc:/flags/UI/Images/flags/orkney islands.png";
        case "Ossetia": return "qrc:/flags/UI/Images/flags/ossetia.png";
        case "Pakistan": return "qrc:/flags/UI/Images/flags/pakistan.png";
        case "Palau": return "qrc:/flags/UI/Images/flags/palau.png";
        case "Palestine": return "qrc:/flags/UI/Images/flags/palestine.png";
        case "Panama": return "qrc:/flags/UI/Images/flags/panama.png";
        case "Papua New Guinea": return "qrc:/flags/UI/Images/flags/papua new guinea.png";
        case "Paraguay": return "qrc:/flags/UI/Images/flags/paraguay.png";
        case "Peru": return "qrc:/flags/UI/Images/flags/peru.png";
        case "Philippines": return "qrc:/flags/UI/Images/flags/philippines.png";
        case "Pitcairn Islands": return "qrc:/flags/UI/Images/flags/pitcairn islands.png";
        case "Poland": return "qrc:/flags/UI/Images/flags/poland.png";
        case "Portugal": return "qrc:/flags/UI/Images/flags/portugal.png";
        case "Puerto Rico": return "qrc:/flags/UI/Images/flags/puerto rico.png";
        case "Qatar": return "qrc:/flags/UI/Images/flags/qatar.png";
        case "Rapa Nui": return "qrc:/flags/UI/Images/flags/rapa nui.png";
        case "Republic of Macedonia": return "qrc:/flags/UI/Images/flags/republic of macedonia.png";
        case "Republic of the Congo": return "qrc:/flags/UI/Images/flags/republic of the congo.png";
        case "Romania": return "qrc:/flags/UI/Images/flags/romania.png";
        case "Russia": return "qrc:/flags/UI/Images/flags/russia.png";
        case "Rwanda": return "qrc:/flags/UI/Images/flags/rwanda.png";
        case "Saba Island": return "qrc:/flags/UI/Images/flags/saba island.png";
        case "Sahrawi Arab Democratic Republic": return "qrc:/flags/UI/Images/flags/sahrawi arab democratic republic.png";
        case "Samoa": return "qrc:/flags/UI/Images/flags/samoa.png";
        case "San Marino": return "qrc:/flags/UI/Images/flags/san marino.png";
        case "Sao Tome and Prince": return "qrc:/flags/UI/Images/flags/sao tome and prince.png";
        case "Sardinia": return "qrc:/flags/UI/Images/flags/sardinia.png";
        case "Saudi Arabia": return "qrc:/flags/UI/Images/flags/saudi arabia.png";
        case "Scotland": return "qrc:/flags/UI/Images/flags/scotland.png";
        case "Senegal": return "qrc:/flags/UI/Images/flags/senegal.png";
        case "Serbia": return "qrc:/flags/UI/Images/flags/serbia.png";
        case "Seychelles": return "qrc:/flags/UI/Images/flags/seychelles.png";
        case "Sierra Leone": return "qrc:/flags/UI/Images/flags/sierra leone.png";
        case "Singapore": return "qrc:/flags/UI/Images/flags/singapore.png";
        case "Sint Eustatius": return "qrc:/flags/UI/Images/flags/sint eustatius.png";
        case "Sint Maarten": return "qrc:/flags/UI/Images/flags/sint maarten.png";
        case "Slovakia": return "qrc:/flags/UI/Images/flags/slovakia.png";
        case "Slovenia": return "qrc:/flags/UI/Images/flags/slovenia.png";
        case "Solomon Islands": return "qrc:/flags/UI/Images/flags/solomon islands.png";
        case "Somalia": return "qrc:/flags/UI/Images/flags/somalia.png";
        case "Somaliland": return "qrc:/flags/UI/Images/flags/somaliland.png";
        case "South Africa": return "qrc:/flags/UI/Images/flags/south africa.png";
        case "South Korea": return "qrc:/flags/UI/Images/flags/south korea.png";
        case "South Sudan": return "qrc:/flags/UI/Images/flags/south sudan.png";
        case "Spain": return "qrc:/flags/UI/Images/flags/spain.png";
        case "Sri Lanka": return "qrc:/flags/UI/Images/flags/sri lanka.png";
        case "St Barts": return "qrc:/flags/UI/Images/flags/st barts.png";
        case "St Lucia": return "qrc:/flags/UI/Images/flags/st lucia.png";
        case "St Vincent and the Grenadines": return "qrc:/flags/UI/Images/flags/st vincent and the grenadines.png";
        case "Sudan": return "qrc:/flags/UI/Images/flags/sudan.png";
        case "Suriname": return "qrc:/flags/UI/Images/flags/suriname.png";
        case "Swaziland": return "qrc:/flags/UI/Images/flags/swaziland.png";
        case "Sweden": return "qrc:/flags/UI/Images/flags/sweden.png";
        case "Switzerland": return "qrc:/flags/UI/Images/flags/switzerland.png";
        case "Syria": return "qrc:/flags/UI/Images/flags/syria.png";
        case "Taiwan": return "qrc:/flags/UI/Images/flags/taiwan.png";
        case "Tajikistan": return "qrc:/flags/UI/Images/flags/tajikistan.png";
        case "Tanzania": return "qrc:/flags/UI/Images/flags/tanzania.png";
        case "Thailand": return "qrc:/flags/UI/Images/flags/thailand.png";
        case "Tibet": return "qrc:/flags/UI/Images/flags/tibet.png";
        case "Togo": return "qrc:/flags/UI/Images/flags/togo.png";
        case "Tokelau": return "qrc:/flags/UI/Images/flags/tokelau.png";
        case "Tonga": return "qrc:/flags/UI/Images/flags/tonga.png";
        case "Transnistria": return "qrc:/flags/UI/Images/flags/transnistria.png";
        case "Trinidad and Tobago": return "qrc:/flags/UI/Images/flags/trinidad and tobago.png";
        case "Tunisia": return "qrc:/flags/UI/Images/flags/tunisia.png";
        case "Turkey": return "qrc:/flags/UI/Images/flags/turkey.png";
        case "Turkmenistan": return "qrc:/flags/UI/Images/flags/turkmenistan.png";
        case "Turks and Caicos": return "qrc:/flags/UI/Images/flags/turks and caicos.png";
        case "Tuvalu": return "qrc:/flags/UI/Images/flags/tuvalu.png";
        case "Uganda": return "qrc:/flags/UI/Images/flags/uganda.png";
        case "Ukraine": return "qrc:/flags/UI/Images/flags/ukraine.png";
        case "United Arab Emirates": return "qrc:/flags/UI/Images/flags/united arab emirates.png";
        case "United Kingdom": return "qrc:/flags/UI/Images/flags/united kingdom.png";
        case "United Nations": return "qrc:/flags/UI/Images/flags/united nations.png";
        case "United States": return "qrc:/flags/UI/Images/flags/united states.png";
        case "Uruguay": return "qrc:/flags/UI/Images/flags/uruguay.png";
        case "Uzbekistan": return "qrc:/flags/UI/Images/flags/uzbekistan.png";
        case "Vanuatu": return "qrc:/flags/UI/Images/flags/vanuatu.png";
        case "Vatican City": return "qrc:/flags/UI/Images/flags/vatican city.png";
        case "Venezuela": return "qrc:/flags/UI/Images/flags/venezuela.png";
        case "Vietnam": return "qrc:/flags/UI/Images/flags/vietnam.png";
        case "Virgin Islands": return "qrc:/flags/UI/Images/flags/virgin islands.png";
        case "Wales": return "qrc:/flags/UI/Images/flags/wales.png";
        case "Yemen": return "qrc:/flags/UI/Images/flags/yemen.png";
        case "Zambia": return "qrc:/flags/UI/Images/flags/zambia.png";
        case "Zimbabwe": return "qrc:/flags/UI/Images/flags/zimbabwe.png";
        default: return "";
        }
    }

    function mask(str, securityState = false) {
        if(!securityState) {
            return str
        }

        return str.replace(/[^.]/g, '*');
    }
}
